services:
  formula-web:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    restart: "unless-stopped"
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.formula-web.rule=Host(`formula.nooridev.com`)"
      - "traefik.http.routers.formula-web.entrypoints=web"
      - "traefik.http.services.formula-web.loadbalancer.server.port=3000"
  formula-api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    restart: "unless-stopped"
    links:
      - postgres
    depends_on:
      - postgres
    expose:
      - 5000
    labels:	
      - "traefik.enable=true"
      - "traefik.http.routers.formula-api.rule=Host(`formula.nooridev.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.formula-api.entrypoints=web"
      - "traefik.http.services.formula-api.loadbalancer.server.port=5000"
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

networks:
  default:
    external:
      name:
        traefik_default