services:
  formula-web:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    restart: "unless-stopped"
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`formula.nooridev.com`)"
      - "traefik.http.routers.whoami.entrypoints=web"
  formula-api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    restart: "unless-stopped"
    ports:
      - 3001:300
    labels:	
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`formula.nooridev.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.whoami.entrypoints=web"
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data